from __future__ import annotations
import argparse, json
from pathlib import Path


def load(root:Path):
    event=json.loads((root/'output/end_event.json').read_text(encoding='utf-8'))
    scen=json.loads((root/'validation/scenarios/scenario_comparison_refined.json').read_text(encoding='utf-8'))
    rnd=json.loads((root/'validation/numeric/rounding_stability.json').read_text(encoding='utf-8'))
    xls=json.loads((root/'validation/xlsx_readback.json').read_text(encoding='utf-8'))
    table=(root/'output/table5.md').read_text(encoding='utf-8').strip()
    return event,scen,rnd,xls,table

def fmt(root:Path):
    event,scen,rnd,xls,table=load(root)
    crit=event['critical_s']; exe=event['execution_s']; ch=crit/3600; eh=exe/3600
    mean=scen['scenarios']['mean']; nominal=scen['scenarios']['nominal']; tm=scen['scenarios']['time_mean']
    readme=f'''# q3_refinement_delivery\n\n本目录是第三问定向复审后的新交付，不覆盖历史 `q3_final_delivery/`。本轮读取仓库提交 `c1743f6b19d7f357d1bc005310fdb6367a549bec`，针对 206901 s 比较、8 处四位舍入敏感值、自动结束时间和只读验证等问题完成修订。\n\n主口径仍为：前4h使用附件1分段线性环境，之后保持末1h的61个观测点算术均值；固定半径2cm、长度25cm；附录3变物性；轴向均匀一维径向模型；以完整域最大干基含水率严格小于0.15为结束判据。\n\n临界根为 **{crit:.12f} s = {ch:.10f} h**，四位小时为 **{ch:.4f} h**。临界根是等号状态，不满足严格不等号。按0.03s工程数值预算并向上量化到0.0001h后，正式执行端点为 **{exe:.2f} s = {eh:.4f} h**，端点最大含水率为 **{event['execution_max']:.17g} kg/kg**。\n\n正式 `output/result3.xlsx` 共有 {xls['data_rows']} 行数据、{xls['moisture_cells']} 个水分数值单元格，全部来自同一未舍入配置法轨迹。历史有限体积解中8个跨四位舍入分界的单元格已由统一轨迹重导出；N=160 BDF与本轮新跑N=80 BDF对照均实现全表四位 **0** 个差异。\n\n## 运行入口\n\n```bash\npython run_all.py verify --audit-out /path/to/new_audit\npython run_all.py scenario --name nominal --out /path/to/new_nominal.json\npython run_all.py cold-start --out /path/to/new_solution_prefix\n```\n\n`verify` 只读冻结目录，检查结果必须写到新审核目录。`cold-start` 会重新积分，耗时显著高于只读验收；已有正式文件不会被覆盖。\n\n## 目录索引\n\n- `第三问最终复审与答案.md`：最终结论、证据和可定稿边界。\n- `206901秒与当前答案的比较.md`：统一环境、判据和取整口径。\n- `审核意见逐项回应.md`：对审核任务书发现逐项回应。\n- `第三问论文正文.md`：可直接并入论文的第三问正文。\n- `output/`：正式Excel、未舍入数组、表5、事件JSON与图。\n- `validation/`：全表舍入、场景、历史收敛、几何与运行工具证据。\n- `source/`：求解、环境场景、导出、只读核验及文档生成代码。\n\n## 仍需保留的边界\n\n57.4741h是上述条件模型下的执行时长，不是脱离未来环境、端面交换和物理闭合的唯一实测真值。末小时“61点算术均值”和“分段线性曲线时间平均”不是同一统计量，本轮已分别实算，后者临界时间比主口径晚 {tm['critical_s']-mean['critical_s']:.3f}s。\n'''

    final=f'''# 第三问最终复审与答案\n\n## 1. 最终裁定\n\n在“前4h附件环境分段线性插值、4h后保持末1h的61点算术均值、固定几何、附录3有效物性、一维径向模型”的口径下，第三问可以定稿。连续临界根为 **{crit:.12f}s（{ch:.10f}h）**，论文四位写作 **{ch:.4f}h**；严格执行时长为 **{exe:.2f}s（{eh:.4f}h）**。\n\n严格条件是全域最大含水率小于0.15。根本身的最大值等于0.15，因此只代表达标集合的下确界；正式执行端点重新计算完整空间场，最大值为 **{event['execution_max']:.17g}**，最湿点位于轴心，严格满足题意。\n\n## 2. 数值方法与统一输出\n\n正式Excel不再沿用有限体积主轨迹中靠近十进制中点的8个显示值，而是从一条完整的Chebyshev配置/Radau未舍入轨迹统一导出。该轨迹使用原函数梯度处理低含水率强非线性扩散，并用代数Robin边界处理表面节点。\n\n空间加严的N=160 BDF参考与正式轨迹在全部72429个Excel水分单元格上四位显示完全一致，最大未舍入差约 **{rnd['official_vs_reference160']['max_abs_difference_kgkg']:.3e}**。本轮新跑的N=80 BDF时间方法检查同样实现全表四位0差异。\n\n历史N=2048有限体积主解与该正式轨迹的最大未舍入差约 **{rnd['historical_fv_vs_refined_official']['max_abs_difference_kgkg']:.3e}**，仅8格跨越四位舍入分界；这些差异不影响表5、结束事件或时长。修订版没有逐格手改，而是整张工作簿由统一轨迹重新生成。\n\n## 3. 表5\n\n{table}\n\n## 4. 206901 s与未来环境\n\n相同N=2048有限体积空间离散、时间设置和全域判据下，主均值平台在206901s的最大含水率为 **{mean['Cmax_206901']:.16f}**，仍大于0.15，因此206901s在主口径下不合格。主口径临界值为 **{mean['critical_s']:.6f}s**。\n\n若4h后改用名义平台50℃、0.05，则临界值为 **{nominal['critical_s']:.6f}s**，执行端点为 **{nominal['execution_s']:.2f}s**；此时206901s最大含水率为 **{nominal['Cmax_206901']:.16f}**，已经严格达标。因此206901可由不同未来环境口径解释，但不能据数字反推出他人的真实配置。\n\n把末小时分段线性曲线作时间积分平均，则平台为T={tm['future_T_C']:.9f}℃、C={tm['future_C_kgkg']:.12f}kg/kg，临界值为 **{tm['critical_s']:.6f}s**，比61点算术均值主口径晚 **{tm['critical_s']-mean['critical_s']:.3f}s**。未来平台定义对末几秒的影响明显大于毫秒级求解差。\n\n## 5. 几何与物理适用范围\n\n主答案明确采用轴向均匀径向有效模型。历史有限圆柱匹配网格显示端面交换会造成秒级变化，但轴向加密尚不足以给二维四位小时误差证书，因此本轮不把粗二维绝对时间替换成主时长，也不把几何差异吸收到0.03s数值预算。\n\n模型仍未独立闭合潜热、携焓、真实吸附等温线和收缩。题给数据不足以无歧义辨识这些扩展所需参数，故本轮保持题给有效模型，并将未来边界、传质系数和端部影响作为条件敏感性，而不是凭其他食品参数创造唯一“真实修正值”。\n\n## 6. 定稿判断\n\n第三问在上述明确假设下可以进入论文定稿：时长、表5、完整Excel、全域严格判据和源码链路相互一致。论文必须同时说明4h以后环境是延拓假设，并区分连续临界根与严格执行时间；不能把206906.76s解释为实验置信上界。\n'''

    cmp=f'''# 206901秒与当前答案的比较\n\n比较时必须同时统一未来环境、几何、全域判据、数值分辨率和取整规则。当前主口径使用末小时61点算术均值平台；在同一N=2048有限体积模型中，206901s时全域最大含水率为 **{mean['Cmax_206901']:.16f} > 0.15**，最湿位置仍在轴心，因此尚未达标。\n\n主口径连续临界时间为 **{mean['critical_s']:.6f}s**，而正式执行时间为 **{mean['execution_s']:.2f}s**。前者是M(t)=0.15的等号根，后者是在工程数值预算后向上量化到0.0001h并重新评价全场的严格合格时刻，二者不能与“向上取整到整数秒”混用。\n\n名义平台50℃、0.05下，精细N=2048续算临界值为 **{nominal['critical_s']:.6f}s**，执行端点为 **{nominal['execution_s']:.2f}s**，206901s时最大含水率为 **{nominal['Cmax_206901']:.16f} < 0.15**。因此206901s在这一不同环境假设下确实合理。\n\n末小时分段线性曲线的时间平均平台则给出 **{tm['critical_s']:.6f}s** 的临界值，比主口径晚 **{tm['critical_s']-mean['critical_s']:.3f}s**。61点样本算术均值与曲线时间平均权重不同，二者均可作为外推假设，但必须明确选择，不能混写成同一个“末小时平均”。\n\n目前没有对方完整代码、环境延拓、网格和全场数据，因此不能宣称已查明206901s的外部来源。可以确定的是：相同主模型下206901s不合格；名义平台下206901s已合格；数字更短本身不构成模型更准确的证据。\n'''

    response=f'''# 审核意见逐项回应\n\n| 审核发现 | 处理 | 证据 |\n|---|---|---|\n| 206901与206906.76口径混杂 | 采纳并修复 | `validation/scenarios/scenario_comparison_refined.json` |\n| 61点算术均值与时间平均混写风险 | 采纳并分场景实算 | `mean_N2048.json`、`time_mean_N2048.json` |\n| Excel有8处四位舍入敏感值 | 采纳；整表由统一配置法轨迹重导出，不手改单元格 | `validation/numeric/rounding_stability.json` |\n| 固定执行端点 | 采纳；新求解器由根、预算和0.36s量化自动生成端点 | `source/q3_refined_reference.py` |\n| 报告旧数字硬编码 | 采纳；文档由当前JSON动态生成 | `source/build_documents.py` |\n| verify原地改写 | 采纳；冻结核验只读，审核输出必须写到外部目录 | `source/verify_frozen.py` |\n| 孤立NPZ仍可能被覆盖 | 采纳；JSON或NPZ任一存在即拒绝输出 | `source/q3_refined_reference.py`、运行反例 |\n| Excel检查会放过额外列/错误单位 | 采纳；严格检查唯一Sheet1、A1:Vn、标题、类型、格式和值 | `source/validate_xlsx.py` |\n| 二维80×128缺口 | 部分采纳；本轮主答案仍是一维，未把未收敛二维替换为正式答案 | `validation/geometry/` |\n| 无数据扩张潜热/吸附/收缩 | 不作为本轮主线 | `第三问论文正文.md`、文献说明 |\n\n8处旧差异现在全部有统一处理：正式轨迹与N=160 BDF参考、以及本轮新跑N=80 BDF检查，对72429个Excel水分值均实现四位0差异。旧有限体积值仍保留在历史交付和差分JSON中，便于追溯而不覆盖证据。\n'''

    paper=f'''# 第三问论文正文\n\n## 3 药材达到含水率要求的烘干时长\n\n第三问要求药材各处干基含水率均低于0.15kg/kg。沿用第二问附录3变物性模型，并保持半径2cm、长度25cm不变。本文主模型采用轴向均匀的径向圆柱近似，中心为对称零通量边界，表面采用与前两问一致的对流换热和等效传质边界。\n\n附件1仅给出0—4h烘房环境。0—4h使用观测值的分段线性插值；4h以后取末1h共61个观测点的算术均值，即T∞={event['future_T_C']:.6f}℃、C∞={event['future_C_kgkg']:.9f}kg/kg，并将其作为恒温阶段的工作延拓假设。该外推不是4h后的实测值。\n\n含水率方程采用局部变扩散系数D(T,C)，并对D=A(T)exp(-0.45/C)中的浓度因子引入原函数F，使离散面通量直接逼近A(T)∇F(C)。正式结果采用全局配置法独立轨迹，历史守恒有限体积法、加密配置法及不同时间推进方法用于核验长时低含水率阶段。\n\n定义M(t)=max C(r,t)。连续临界时刻t*满足M(t*)=0.15，严格要求M<0.15，因此t*本身并非可执行的合格状态。数值求得t*={crit:.6f}s={ch:.6f}h，四位小时为{ch:.4f}h；临界附近最大含水率单调下穿，最湿位置为轴心。\n\n考虑空间、时间和独立方法的实测差异后，采用0.03s工程数值预算，并把执行时间向上量化到0.0001h。由此得到正式结束时间{exe:.2f}s={eh:.4f}h。该时刻未舍入全域最大含水率为{event['execution_max']:.16f}，严格小于0.15。\n\n每6h及结束时刻的径向含水率见表5。\n\n{table}\n\n完整的60s×0.1cm结果写入`result3.xlsx`。文件从60s开始，最后完整分钟为206880s，并补入非整分钟执行端点{exe:.2f}s。末行中心值四位显示为0.1500，但未舍入值小于0.15，故达标判断始终基于未舍入完整场，而非显示值。\n\n对全工作簿72429个水分数值，N=160空间加密参考与另一时间推进方法均在四位显示上与正式轨迹完全一致。历史有限体积轨迹仅有8个靠近十进制舍入中点的单元格出现末位差异，最大未舍入差为{rnd['historical_fv_vs_refined_official']['max_abs_difference_kgkg']:.3e}kg/kg，不改变表5和终止事件。\n\n未来环境是本题长期预测的主要条件之一。同一N=2048模型下，若改用名义平台50℃、0.05，临界时间变为{nominal['critical_s']:.3f}s，比主口径提前{mean['critical_s']-nominal['critical_s']:.3f}s；若用末小时分段线性曲线的时间平均，则临界时间为{tm['critical_s']:.3f}s，比主口径推迟{tm['critical_s']-mean['critical_s']:.3f}s。\n\n因此本文最终给出：在末小时61点算术均值平台及一维径向有效模型下，药材临界烘干时长为**{ch:.4f}h**，工程执行时长取**{eh:.4f}h**。该结论不等同于真实烘房未来控制和完整有限圆柱物理下的唯一实验时长，端部交换及气固平衡映射等仍属于模型条件。\n'''
    return {'README.md':readme,'第三问最终复审与答案.md':final,'206901秒与当前答案的比较.md':cmp,'审核意见逐项回应.md':response,'第三问论文正文.md':paper}

def generate(root:Path):
    for name,text in fmt(root).items():
        (root/name).write_text(text,encoding='utf-8')

if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('--root',type=Path,default=Path(__file__).resolve().parents[1]);a=p.parse_args();generate(a.root)
