"""Enlarge two validation figures using frozen inputs and original drawing code.

Only font sizes and non-data layout are changed. No PDE, time integration,
parameter scenario, or formal numerical result is generated by this script.
"""
from pathlib import Path
import copy
import json

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib.text import Text, Annotation
from matplotlib import font_manager

from build_font_assets import load_module, apply_fonts, content_signature, sha, FAMILIES

BASE = Path(__file__).resolve().parent
ROOT = BASE.parents[1]
OUT = BASE / 'figures/legibility_validation'
EVIDENCE = BASE / 'evidence/figure_legibility_20260913/validation'
BASELINE = '4f09fdad4182b6f220e801af54dffd0be37ad04c'
WIDTHS_CM = {'dimension_reduction': 14.7, 'environment_sensitivity': 13.95}


def scientific_signature(signature):
    """Exclude only intentionally edited typography and layout positions."""
    signature = copy.deepcopy(signature)
    signature.pop('anchors')
    for ax in signature['axes']:
        ax.pop('bounds')
    for text in signature['texts']:
        text.pop('size_pt')
    return signature


def enlarge_reduction(fig):
    # The source is inserted at 14.7/16.4: 10.6 pt becomes 9.50 pt.
    for text in fig.findobj(Text):
        text.set_fontsize(10.6)
    for i, ax in enumerate(fig.axes[:3]):
        ax.set_position([.070 + .314 * i, .570, .262, .240])
        ax.xaxis.label.set_fontsize(10.9)
        ax.xaxis.labelpad = 3
        for text in ax.texts:
            text.set_fontsize(10.6)
            text.set_position((0, 1.022))
        title = fig.texts[i+1]
        title.set_fontsize(11.7)
        title.set_position((.070 + .314 * i, .887))
    fig.texts[0].set_fontsize(11.2)
    fig.texts[0].set_position((.070, .994))
    fig.texts[4].set_fontsize(11.7)
    fig.texts[4].set_position((.070, .390))
    fig.texts[5].set_fontsize(10.6)
    fig.texts[5].set_position((.978, .390))
    fig.legends[0].set_bbox_to_anchor((.490, .411))
    lower = fig.axes[3]
    lower.set_position([.230, .185, .558, .189])
    lower.xaxis.label.set_fontsize(10.9)
    lower.xaxis.labelpad = 4
    lower.tick_params(axis='y', pad=20)
    for text in lower.texts:
        if not isinstance(text, Annotation):
            text.set_position((1.340, text.get_position()[1]))
    fig.texts[-1].set_position((.070, .015))
    fig.texts[-1].set_fontsize(10.6)


def enlarge_environment(fig):
    # The source is inserted at 13.95/16.4: 11.2 pt becomes 9.53 pt.
    for text in fig.findobj(Text):
        text.set_fontsize(11.2)
    ax = fig.axes[0]
    ax.set_position([.218, .275, .756, .533])
    ax.xaxis.label.set_fontsize(11.4)
    ax.xaxis.labelpad = 4
    for j, text in enumerate(ax.texts):
        if isinstance(text, Annotation):
            x, _ = text.get_position()
            # Paired data points retain their original y coordinates. Only the
            # adjacent numeric labels move 2 pt outward to separate text rows.
            text.set_position((x, 2 if j < 4 else -2))
    fig.texts[0].set_fontsize(12.4)
    fig.texts[0].set_position((.040, .940))
    fig.legends[0].set_bbox_to_anchor((.992, .940))
    fig.texts[-1].set_position((.040, .030))
    fig.texts[-1].set_fontsize(11.2)


def text_bounds(fig):
    renderer = fig.canvas.get_renderer()
    checks = []
    for text in fig.findobj(Text):
        if not text.get_visible() or not text.get_text():
            continue
        box = text.get_window_extent(renderer)
        inside = (box.x0 >= -.5 and box.y0 >= -.5 and
                  box.x1 <= fig.bbox.width+.5 and box.y1 <= fig.bbox.height+.5)
        checks.append({'text': text.get_text(), 'source_font_pt': text.get_fontsize(),
                       'inside_canvas': bool(inside), 'bounds_pixels': list(box.bounds)})
        assert inside, (text.get_text(), box.bounds, fig.bbox.bounds)
    return checks


def assert_no_text_overlap(checks):
    for i, first in enumerate(checks):
        ax, ay, aw, ah = first['bounds_pixels']
        for second in checks[i+1:]:
            bx, by, bw, bh = second['bounds_pixels']
            overlap_x = min(ax+aw, bx+bw)-max(ax, bx)
            overlap_y = min(ay+ah, by+bh)-max(ay, by)
            assert overlap_x <= .5 or overlap_y <= .5, (first['text'], second['text'])


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    EVIDENCE.mkdir(parents=True, exist_ok=True)
    common = load_module('common', BASE / 'visual_revision/common.py')
    common.OUT, common.EVIDENCE, common.BASELINE = OUT, EVIDENCE, BASELINE
    records = {}

    def save_enlarged(evidence, fig, name):
        assert name in WIDTHS_CM
        apply_fonts(fig)
        fig.canvas.draw()
        before = content_signature(fig)
        old_check_path = evidence.source(
            'paper/q1234_draft_v1/evidence/figure_fonts_20260912/font_content_check.json',
            'Previously accepted plotted-content signature; read only')
        old_check = json.loads(old_check_path.read_text(encoding='utf-8'))
        assert json.loads(json.dumps(before)) == old_check['figures'][name]['content'], name
        if name == 'dimension_reduction':
            enlarge_reduction(fig)
        else:
            enlarge_environment(fig)
        apply_fonts(fig)
        fig.canvas.draw()
        after = content_signature(fig)
        assert scientific_signature(before) == scientific_signature(after), name
        bounds = text_bounds(fig)
        assert_no_text_overlap(bounds)
        scale = WIDTHS_CM[name] / 16.4
        for item in bounds:
            item['paper_font_pt'] = item['source_font_pt'] * scale
        old = BASE / 'figures/font_revision' / f'{name}.pdf'
        records[name] = {
            'prior_pdf': old.relative_to(ROOT).as_posix(), 'prior_sha256': sha(old),
            'inserted_width_cm': WIDTHS_CM[name], 'source_width_cm': 16.4,
            'canvas_dimensions_unchanged': before['size_inches'] == after['size_inches'],
            'scientific_signature_unchanged': True,
            'baseline_signature_matches_accepted_font_record': True,
            'visible_text_bounds_nonoverlapping': True,
            'scientific_signature': scientific_signature(after),
            'before': before, 'after': after, 'text_bounds': bounds,
        }
        for ext in ('pdf', 'svg', 'png'):
            path = OUT / f'{name}.{ext}'
            opts = {'dpi': 400}
            if ext == 'pdf':
                opts['metadata'] = {'CreationDate': None, 'ModDate': None}
            elif ext == 'svg':
                opts['metadata'] = {'Date': None}
            fig.savefig(path, **opts)
            evidence.outputs[path.relative_to(ROOT).as_posix()] = {
                'sha256': sha(path), 'bytes': path.stat().st_size}
        plt.close(fig)

    common.Evidence.save = save_enlarged
    module = load_module('legibility_validation_original', BASE / 'visual_revision/validation.py')
    plt.rcParams.update({'svg.fonttype': 'path', 'svg.hashsalt': 'validation-legibility-20260913'})
    module.main()
    source_record = EVIDENCE / 'validation_sources.json'
    source_data = json.loads(source_record.read_text(encoding='utf-8'))
    source_data['font_wrapper'] = {'path': Path(__file__).relative_to(ROOT).as_posix(),
                                   'sha256': sha(__file__)}
    source_data['details']['font'] = {'chinese': 'SimSun', 'latin_and_digits': 'Times New Roman',
                                     'mathtext': 'Times New Roman custom regular/italic/bold'}
    source_record.write_text(json.dumps(source_data, ensure_ascii=False, indent=2)+'\n', encoding='utf-8')
    fonts = {name: str(font_manager.findfont(name, fallback_to_default=False)) for name in FAMILIES}
    result = {
        'baseline_commit': BASELINE, 'builder': Path(__file__).relative_to(ROOT).as_posix(),
        'builder_sha256': sha(__file__),
        'scope': 'Frozen input graphical postprocessing only; no solver or scenario run.',
        'font_files': fonts, 'font_file_sha256': {k: sha(v) for k, v in fonts.items()},
        'figure_3_reference': {'ticks_notes_paper_pt': 9.46, 'axes_paper_pt': 9.72,
                               'titles_paper_pt': 10.49},
        'figures': records,
        'permitted_changes': ['font sizes', 'text and legend positions', 'axes rectangles',
                              'annotation offset points and padding'],
        'preserved': ['all displayed strings', 'all plotted arrays and marker coordinates',
                      'all axis limits scales and ticks', 'all colours', 'figure dimensions'],
    }
    (EVIDENCE / 'content_and_legibility_check.json').write_text(
        json.dumps(result, ensure_ascii=False, indent=2)+'\n', encoding='utf-8')
    print('Validation figures enlarged; scientific content and saved inputs unchanged.')


if __name__ == '__main__':
    main()
